name: spending_management
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  velocity_x: ^3.4.0
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  fluttertoast: ^8.0.9
  mask_text_input_formatter: ^2.3.0
  shared_preferences: ^2.0.15
  pinput: ^2.2.8
  flutter_screenutil: ^5.5.2
  firebase_auth: ^3.4.2
  firebase_core: ^1.19.2
  cloud_firestore: ^3.3.0
  # firebase_messaging: ^11.3.0
  # flutter_local_notifications: ^9.5.2
  #paint dotted border
  path_drawing: ^1.0.0
  #remove sign in vietnam language
  tiengviet: ^0.5.0
  flutter_localizations:
    sdk: flutter

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansJP-Bold.otf
        - asset: assets/fonts/NotoSansJP-Black.otf
        - asset: assets/fonts/NotoSansJP-Medium.otf
        - asset: assets/fonts/NotoSansJP-Light.otf
        - asset: assets/fonts/NotoSansJP-Regular.otf
        - asset: assets/fonts/NotoSansJP-Thin.otf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
