name: spending_management
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  velocity_x: ^3.4.0
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  mask_text_input_formatter: ^2.3.0
  shared_preferences: ^2.0.15
  pinput: ^2.2.8

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
